name: Build, Test, and Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.6

    - name: Initialize Maven Wrapper
      run: mvn -N wrapper:wrapper

    - name: Build with Maven
      run: ./mvnw clean package

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.6

    - name: Initialize Maven Wrapper
      run: mvn -N wrapper:wrapper

    - name: Run tests with Maven
      run: ./mvnw test

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "Skipping authentication for public registry"

    - name: Build and push Docker image
      run: |
        docker build -t hello-world-spring:latest .
        docker tag hello-world-spring:latest public-registry/hello-world-spring:latest
        docker push public-registry/hello-world-spring:latest